controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_actions:
    resource: ../../src/Action/Api
    prefix: /api
    name_prefix: api_
    type: annotation